### ISSUE TITLE
What constitutes an Old or Modern Emulator for the 2.5.0 version?

### ISSUE THREAD

**Issue by marcelodmc3** [tewtal/sm_practice_hack#110]
Hi! I just saw that the 2.5.0 version is available and I'm confused on which version to download.

I currently use SNES9X 1.60. Do I need to download the one for Old Emulators or Modern Emulators?

![image](https://user-images.githubusercontent.com/5389879/191588358-c5640e7b-e514-48bd-8e1d-bd7ffe389ff0.png)

Thank you.

**Comment by NobodyNada** [comment]
AFAIK SNES9X should support the “Modern Emulators” build just fine, so I’d try that one (and fall back to “Older Emulators” if you have any problems with it).

**Comment by InsaneFirebat** [comment]
Snes9x v1.43 (which is forbidden in speedrunning) was the only PC emulator I found that required the third option, while the latest version (1.61) can run all three practice hacks.
