### ISSUE TITLE
Removing an unequipped item via the equipment menu equips the item

### ISSUE THREAD

**Issue by idlechild** [tewtal/sm_practice_hack#118]
Previously removing an equipped item via the equipment menu left the item equipped, which is also wrong.  However I'm so used to avoiding that issue that I unequipped the items via the vanilla menu first and then removed the items, and now everything I removed gets equipped.

**Comment by InsaneFirebat** [comment]
I just merged a few pulls into the `next-update` branch, including a big change to the item/beams menus. I can't reproduce the issue with those changes.
