### ISSUE TITLE
Opening/closing practice rom menu changes the tint/coloring at landing side

### ISSUE THREAD

**Issue by idlechild** [tewtal/sm_practice_hack#121]
May affect other rooms, I just happened to be testing landing site.  No idea if this is a new issue or years old issue, just thought I'd report it.

**Comment by InsaneFirebat** [comment]
Fixed in commit https://github.com/tewtal/sm_practice_hack/commit/0e9c7a5c648356809539b30053e10e660a9bc1ac #140
