### ISSUE TITLE
100% Early Croc Leaving Phantoon preset shows gray screen

### ISSUE THREAD

**Issue by EXAKT-Science** [tewtal/sm_practice_hack#148]
"Leaving Phantoon" preset in 100% Early Croc doesn't display the room properly, with Samus and all tiles but the door being covered with horizontal gray bars. Bomb and PBs will display, but no other projectiles. The "Samus on Top" Sprite Features setting will show her properly, and using X-Ray will show the room normally, even outside of the X-Ray cone. Screenshot attached.
![leaving_phantoon_preset_bug](https://user-images.githubusercontent.com/119459340/221433105-f72d793c-99a1-4bc3-b928-bc8479f41d52.png)

**Comment by InsaneFirebat** [comment]
This also affects any preset that starts in Bowling Room. Custom presets as well.

**Comment by InsaneFirebat** [comment]
Apparently this doesn't affect Bowling Room anymore. [b5ee6a7](https://github.com/InsaneFirebat/sm_practice_hack/commit/b5ee6a7ede6196532de7eee63a81cc7402fa22d0) is a hacky fix to clear and reload BG2 if a preset loads into Phantoon's room.
