### ISSUE TITLE
Menu lockout due to deleting shortcut

### ISSUE THREAD

**Issue by InsaneFirebat** [tewtal/sm_practice_hack#199]
Line 3024 @ https://github.com/tewtal/sm_practice_hack/commit/3c6c71d7d5d2c548bdb28e7d757dd6132fc49752#diff-1f492fb74be8f338307cb39094427de03cafb68428b7c81a6a25fce36287a32bR3024

Old:
```    LDA.w #!sram_ctrl_menu : CMP !DP_CtrlInput : BEQ .end```
New:
```    LDA.w !sram_ctrl_menu : CMP !DP_CtrlInput : BEQ .end```

That was supposed to be an immediate. It's checking if you're editing the menu shortcut, and refusing to delete it if so. DP_CtrlInput holds the address, rather than an input.

Assigning to you since you'll probably submit a pull before I will.

**Comment by idlechild** [comment]
Ah I think I changed that just because it looked wrong.

Alright if you're saying the # should be there
