### ISSUE TITLE
Metronome; cannot change the frequency

### ISSUE THREAD

**Issue by tonysergi** [tewtal/sm_practice_hack#213]
I cannot change the metronome frequency; it defaults to 10, and any DPAD press just beeps, and it flips between 1 and 255.
This is with a rom patched for everdrive X6, generated via the website on June 26th if that leads to any additional information.

**Comment by InsaneFirebat** [comment]
We've got a fix for this coming in the next update.

**Comment by InsaneFirebat** [comment]
To fix this for yourself in the current version, you can use the memory editor to set address $702038 to your desired tickrate. This is the same address that the Metronome menu option is altering. The default is 0A, which is every 10 frames.

InfoHUD > Customize RAM Watch
Set bank byte to $70
Set high byte to $20
Set low byte to $38
Set write value to your desired tickrate
Select write to address
