### ISSUE TITLE
GT-Code Classic Category,Regarding the issue of the reserve tank being set to AUTO

### ISSUE THREAD

**Issue by lightquarz** [tewtal/sm_practice_hack#219]
Check the GT-Code Classic category.
If it is an RTA, the reserve tank mode will be Manual from the time the GT-Code is executed until the end of the game.
Why is the reserve tank mode set to AUTO from the plowerhouse section onwards?
https://github.com/tewtal/sm_practice_hack/blob/3e1f2e33890f93275333573f6d5cdf90b0da4c3c/src/presets/gtclassic_data.asm#L1309

**Comment by InsaneFirebat** [comment]
The reserves will automatically set themselves to auto if you collect a drop that brings you above full energy. This commonly occurs when collecting drops from the metal ninja pirates.

**Comment by lightquarz** [comment]
I checked again as per your advice. Thank you.
This is the same as the vanilla rom.

**Comment by lightquarz** [comment]
I checked again as per your advice. Thank you.
This is the same as the vanilla rom.
