### ISSUE TITLE
Website caches headered roms

### ISSUE THREAD

**Issue by TarThoron** [tewtal/sm_practice_hack#33]
Headered roms are obviously bad, but if you upload one there's no warning or error, and you have to clear the cache to reupload. It would be good to have the website either auto-strip or reject headered roms, or at least have a button to upload a different rom.

**Comment by InsaneFirebat** [comment]
I believe this is known, but good to have it documented. If you're still stuck with this issue, try clearing the cookies for the website to get back to the upload button.

**Comment by tewtal** [comment]
This will be fixed with PR #53
