### ISSUE TITLE
Feature Request: Sub-menus for selecting possible Phantoon patterns

### ISSUE THREAD

**Issue by jberq** [tewtal/sm_practice_hack#62]
Sub-menus for each Phantoon phase with checkboxes toggling the possible patterns which could appear would be useful both for players learning Phantoon as well as those optimizing and practicing the fight.

If a player learned, say, Fast Left 1 and then learned Fast Right 1, they could then practice Fast Left 1 _or_ Fast Right 1. The RNG wouldn't necessarily even need to resemble Phantoon's actual RNG— as long as they were reacting to different patterns it would be efficient and valuable practice.

**Comment by InsaneFirebat** [comment]
The reason we don't offer more control over Phantoon patterns is because allows the rare patterns to appear at a much higher rate, even when these settings aren't used. It's been a while since I've looked into this, but I don't remember there being an easy way around it.

**Comment by tewtal** [comment]
Yeah I don't think it's easily doable with just RNG value changes, but we'd probably have to add a separate branch to Phantoon's AI that does the pattern selection so we could implement locked patterns outside of the normal functionality. That way we can leave the original code intact as much as possible. Either way it's a pretty big project most likely, but an interesting one.
