### ISSUE TITLE
Samus turns invisible and background glitches when loading preset

### ISSUE THREAD

**Issue by radon0303** [tewtal/sm_practice_hack#64]
For the KPRD early ice preset when you load Whomple Jump in Maridia the background tiles are all messed up and samus is invisible. Happens in both 2.2.7 and 2.2.8. Can do more testing and provide screenshots if that would help in any way.

**Comment by idlechild** [comment]
That's probably a result of the preset starting in a boss room.  I'm noticing a lot of preset categories have a whomple jump (or equivalent) preset and they all start in precious room except KPDR early ice.

Is it okay if we change the preset to start in the precious room like the other whomple jump presets?

**Comment by radon0303** [comment]
Yeah, that works great!
